USE [master]
GO

/****** Object:  Database [technation]    Script Date: 05/07/2024 15:07:19 ******/
CREATE DATABASE [technation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'technation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\technation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'technation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\technation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [technation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [technation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [technation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [technation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [technation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [technation] SET ARITHABORT OFF 
GO

ALTER DATABASE [technation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [technation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [technation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [technation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [technation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [technation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [technation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [technation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [technation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [technation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [technation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [technation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [technation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [technation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [technation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [technation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [technation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [technation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [technation] SET  MULTI_USER 
GO

ALTER DATABASE [technation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [technation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [technation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [technation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [technation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [technation] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [technation] SET QUERY_STORE = ON
GO

ALTER DATABASE [technation] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [technation] SET  READ_WRITE 
GO

USE [technation]
GO

/****** Object:  Table [dbo].[Notas]    Script Date: 05/07/2024 15:08:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Notas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NomePagador] [nvarchar](150) NOT NULL,
	[NumeroIdentificacao] [nvarchar](300) NOT NULL,
	[DataEmissaoNota] [datetime2](7) NULL,
	[DataCobranca] [datetime2](7) NULL,
	[DataPagamento] [datetime2](7) NULL,
	[Valor] [decimal](14, 2) NOT NULL,
	[NotaFiscal] [nvarchar](max) NOT NULL,
	[BoletoBancario] [nvarchar](max) NOT NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_Notas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


